set autoindent
set expandtab
set tabstop=8 softtabstop=0 expandtab shiftwidth=4 smarttab
set hlsearch
set ignorecase
set incsearch
set smartcase
set wrap
set linebreak
set scrolloff=1
set laststatus=2
set ruler
set wildmenu
set number
set relativenumber
set mouse=a
set title
set background=dark
set autoread
set confirm
set formatoptions+=j
set spell
set wildignore+=.pyc,.swp

syntax on
filetype plugin indent on


execute pathogen#infect()
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 1 && isdirectory(argv()[0]) && !exists("s:std_in") | exe 'NERDTree' argv()[0] | wincmd p | ene | endif

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
